# Generated by Django 4.1.3 on 2022-11-06 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=50)),
                ('quant', models.IntegerField()),
                ('type', models.CharField(max_length=40)),
                ('status', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicament', models.CharField(max_length=50)),
                ('quant', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('status', models.IntegerField()),
                ('requests', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.requests')),
            ],
        ),
    ]
