# Generated by Django 4.1.3 on 2022-11-18 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offers',
            new_name='Offer',
        ),
        migrations.RenameModel(
            old_name='Patient',
            new_name='Patients',
        ),
        migrations.RenameModel(
            old_name='Requests',
            new_name='Request',
        ),
    ]
